### ISSUE TITLE
> My friend I used to be a voluntary, fighter against the fires 🔥.

### ISSUE THREAD

**Issue by EasyCompZLD** [inferno-collection/Fire-Alarm#16]
> My friend I used to be a voluntary, fighter against the fires 🔥.
> 
> Nowadays I have to much work to do and we’ll it might just happen to be that we ourselves developed both hard and software for similar machines, but please read my orginal post again.
> 
> I told you, that the menu doesn’t not respond to any Input, I can press every button or try esc or backspace to exit the menu but nope the only way to exit is by re-logging

That is not what you said at all, and has nothing to do with your issue title.

> I cannot control the panel at all soon as it is opened

Regardless, the code has not been touched in 17 months and worked at the time of publishing. If you are on the Beta branch, and vice versa. This is an old resource and until it is updated I cannot provide any support.

_Originally posted by @cm8263 in https://github.com/inferno-collection/Fire-Alarm/issues/15#issuecomment-781914282_

I changed my initial post. But I did not change a thing because you have written very clearly. Do not alter…. So I did not alter.. but the. The issue remains. Could you look into it please Instead of being so harsh as I no close goodbye. That’s not very kind and there are maybe a lot of peeps which you ask anything  but really you taught that an it engineer is asking something for fun on a forum? Nope so you should at least have conclude. That I already reinstalled the plug-in read the read me a few times more got the pager etc. I I’d it al the system works fine it just not accept mouse clicks but then it was not me who touched that code.  But speaking of you….

**Comment by EasyCompZLD** [comment]
Not to be rude,  but do you know the difference between an dev.  Beta and a public one? Yes you can kan keep developers from asking you questions, but making it public does actually come with real users which are somethings seeing things you might overseeing? Any way you’re also redirecting us to this form if there is no related issue in your wiki last but not least where is the disclaimer. 🙈

**Comment by cm8263** [comment]
> > My friend I used to be a voluntary, fighter against the fires 🔥.
> > Nowadays I have to much work to do and we’ll it might just happen to be that we ourselves developed both hard and software for similar machines, but please read my orginal post again.
> > I told you, that the menu doesn’t not respond to any Input, I can press every button or try esc or backspace to exit the menu but nope the only way to exit is by re-logging
> 
> That is not what you said at all, and has nothing to do with your issue title.
> 
> > I cannot control the panel at all soon as it is opened
> 
> Regardless, the code has not been touched in 17 months and worked at the time of publishing. If you are on the Beta branch, and vice versa. This is an old resource and until it is updated I cannot provide any support.
> 
> _Originally posted by @cm8263 in [#15 (comment)](https://github.com/inferno-collection/Fire-Alarm/issues/15#issuecomment-781914282)_
> 
> I changed my initial post. But I did not change a thing because you have written very clearly. Do not alter…. So I did not alter.. but the. The issue remains. Could you look into it please Instead of being so harsh as I no close goodbye. That’s not very kind and there are maybe a lot of peeps which you ask anything but really you taught that an it engineer is asking something for fun on a forum? Nope so you should at least have conclude. That I already reinstalled the plug-in read the read me a few times more got the pager etc. I I’d it al the system works fine it just not accept mouse clicks but then it was not me who touched that code. But speaking of you….

As I have already said, this code has not been updated in over 17 months, there have been multiple updates to the FiveM platform since then, several of which relate to how NUIs work. As said in [the licence](https://github.com/inferno-collection/Fire-Alarm/blob/master/LICENCE.txt) "THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED", so the fact I have made a Wiki, and reply to issues at all is out of the goodness of my heart, I am not under any obligation to do so. The resource might work, or it might not; it needs to be updated, I have not had time to do that yet, so as I said, until it is updated, I will not spend time providing support for an outdated resource. You getting angry at me will not change that.

> Not to be rude, but do you know the difference between an dev. Beta and a public one? Yes you can kan keep developers from asking you questions, but making it public does actually come with real users which are somethings seeing things you might overseeing? Any way you’re also redirecting us to this form if there is no related issue in your wiki last but not least where is the disclaimer. 🙈

That was a Typo, but I suspect you are putting these messages through some kind of translator, so the meaning was likely lost. What I was trying to say, is if you are on the [Beta Branch](https://github.com/inferno-collection/Fire-Alarm/tree/master), try using the [Alpha Branch](https://github.com/inferno-collection/Fire-Alarm/tree/development), and if you are on the [Alpha Branch](https://github.com/inferno-collection/Fire-Alarm/tree/development), try using the 
[Beta Branch](https://github.com/inferno-collection/Fire-Alarm/tree/master).

I am going to close this issue, if you make another issue, I will take further action to restrict your posting. I am sorry it is not working for you, have a good day.
